I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 340, in script
    Arnav ""
Exception: Sayer 'Arnav' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 340, in script
    Arnav ""
  File "C:\Users\benen\OneDrive\Documents\renpy-7.4.11-sdk/renpy/ast.py", line 681, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\benen\OneDrive\Documents\renpy-7.4.11-sdk/renpy/ast.py", line 574, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'Arnav' is not defined.

Windows-10-10.0.19041
Ren'Py 7.4.11.2266
BCA Literature Club 1.0
Sat Apr  2 17:25:53 2022
